# Generated by Django 3.2.25 on 2024-10-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
            ],
            options={
                'verbose_name': 'Tarefa Celery',
                'verbose_name_plural': 'Tarefas Celery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.taskresult',),
        ),
    ]
