# Generated by Django 5.1.2 on 2024-10-31 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_celerytask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payer', 'date'], name='payments_tr_payer_i_85d3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payee', 'date'], name='payments_tr_payee_i_3bfd33_idx'),
        ),
    ]
